/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "rx_int.h"
#include "SDA0_aliases.h"
#include "SDA0.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "ESPUART.h"
#include "esprx_int.h"
#include "ESP_RST_aliases.h"
#include "ESP_RST.h"
#include "SW2_ISR.h"
#include "SW2_aliases.h"
#include "SW2.h"
#include "ENC_aliases.h"
#include "ENC.h"
#include "Tout_aliases.h"
#include "Tout.h"
#include "LED_T_G_aliases.h"
#include "LED_T_G.h"
#include "LED_T_R_aliases.h"
#include "LED_T_R.h"
#include "LED_H_G_aliases.h"
#include "LED_H_G.h"
#include "LED_H_R_aliases.h"
#include "LED_H_R.h"
#include "ENC_ISR.h"
#include "SW1_aliases.h"
#include "SW1.h"
#include "SW1_ISR.h"
#include "TOUT_ISR.h"
#include "LED_T_Y_aliases.h"
#include "LED_T_Y.h"
#include "LED_H_Y_aliases.h"
#include "LED_H_Y.h"
#include "DEBOUNCE_CLK.h"
#include "Hout_aliases.h"
#include "Hout.h"
#include "HOUT_ISR.h"
#include "mistISR.h"
#include "Clock_1.h"
#include "SDA_CTL.h"
#include "SDA1_aliases.h"
#include "SDA1.h"
#include "SDA2_aliases.h"
#include "SDA2.h"
#include "mistTimer.h"
#include "UART_IntClock.h"
#include "ESPUART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

